version: '3.7'
services:
  app:
    image: flask-python
    environment:
      FLASK_PORT: 8080
      FLASK_DEBUG: 'True'
    networks:
      backend:
        aliases:
          - 'app'

  load_balancer:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    networks:
      backend:

networks:
  backend:
